include:
  - board: nice_nano_v2
    shield: butterfi_left nice_view_ccc nice_view_adapter
  - board: nice_nano_v2
    shield: butterfi_right nice_view_ccc nice_view_adapter
  - board: nice_nano_v2
    shield: settings_reset