include:
  - board: nice_nano_v2
    shield: butterfi_left nice_view_adapter nice_view
  - board: nice_nano_v2
    shield: butterfi_right nice_view_adapter nice_view
  - board: nice_nano_v2
    shield: settings_reset