manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
  projects:
    # Together with the above defined remote, this refers to a module located at
    # https://github.com/remote-name/repository-name
    - name: zmk
      remote: zmkfirmware
      revision: main
      # This points to a west manifest file in the remote module for further imports
      import: app/west.yml